pipeline {
    agent {
        label "cloud-focal"
    }

    options {
        disableConcurrentBuilds()
    }

    stages {
        stage("Setup pnpm") {
            steps {
              nodejs(configId: "npmrc-ro", nodeJSInstallationName: "v22") {
                sh "node -v"
                sh "npm -v"
                sh "pnpm -v || corepack enable pnpm"
                sh "pnpm install:all"
              }
            }
        }

        stage("Scan") {
            steps {
                pulsarBlackduck(bdApplicationId: "cloud-manager", buildType: "FREESTYLE")
                pulsarSonar(jobType: "FREESTYLE", projectName: "cloud-manager", customSrc: true)
            }
        }
    }
}